#
# (c) 2006 EPFL, Lausanne, Switzerland
# Thomas Lochmatter
#

all: example-stdin

example-stdin: example-stdin.cpp CommunicationMessage.cpp CommunicationNMEAInterface.cpp
	g++ example-stdin.cpp CommunicationMessage.cpp CommunicationNMEAInterface.cpp -o example-stdin
