# Makefile for the Multi-Agent Optimization aspect of Talos
# Author: Bharath Keshavamurthy
# Organization: School of Electrical and Computer Engineering, Purdue University, West Lafayette, IN.
# Copyright (c) 2019. All Rights Reserved.

# The path to the firmware and foundational libraries for the e-puck2 bot
GLOBAL_PATH = ../e-puck2_main-processor
# The name of the project
PROJECT = optimize
# C sources
CSRC = talos.c
# C++ sources
# CPPSRC = $(CHCPPSRC) talos.cpp
# Options
# USE_OPT += --specs=nosys.specs
# USE_OPT += -lstdc++
# USE_CPPOPT += -std=c++11
# Include the Makefile corresponding to the e-puck2_main-processor project
include $(GLOBAL_PATH)/Makefile
