# This is a MakeFile for the fully distributed active mesh experiment in the Talos initiative
# Author: Bharath Keshavamurthy
# Organization: School of Electrical and Computer Engineering, Purdue University
# Copyright (c) 2019. All Rights Reserved.

# Project Name
PROJECT_NAME := distributed-active-mesh

# Reference the main MakeFile for the ESP-IDF framework
include $(IDF_PATH)/make/project.mk